### Consulta de productos
GET http://api.snack/productos

### Modificar Productos
PUT http://api.snack/productos/1
Content-Type: application/json

{
    "codBarras":"750105521001",
    "descripcion":"Arroz Integral 3kg",
    "stock":85,
    "precio_unitario":15,
    "creado_por":2,
    "fecha_registro":"2026-06-12"
}
### Adicionar Producto
POST http://api.snack/productos
Content-Type: application/json

{
    "codBarras":"750105521002",
    "descripcion":"prueba nuevo producto 3kg",
    "stock":85,
    "precio_unitario":15,
    "creado_por":2,
    "fecha_registro":"2026-06-12"
}

### Eliminar Producto
DELETE http://api.snack/productos/22
